sudo: false
language: go
go:
  - 1.12.x

# only last commit
git:
  depth: 1

# use vendor dependencys
install: true

notifications:
  email: false

env:
  - GO111MODULE="on"

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell

script: 
  - golint `go list`
  - golint ./lib/*.go
  - go test -v -race `go list`
  - go vet -v `go list`
  - gocyclo *.go
  - gocyclo ./lib/*.go
  - ineffassign *.go
  - ineffassign ./lib/*.go
  - misspell *.go
  - misspell ./lib/*.go
